-- SAM Tavelure V5
-- À exécuter dans Supabase > SQL Editor.
-- Les 7 stades sont créés SANS aucune date d'observation.

create table if not exists public.tavelure_peritheces (
  stade smallint primary key check (stade between 1 and 7),
  date_obs date null,
  updated_at timestamptz not null default now()
);

insert into public.tavelure_peritheces (stade, date_obs)
values
  (1, null),
  (2, null),
  (3, null),
  (4, null),
  (5, null),
  (6, null),
  (7, null)
on conflict (stade) do update
set date_obs = null,
    updated_at = now();

create table if not exists public.tavelure_comptages (
  id bigint generated by default as identity primary key,
  episode text not null,
  date_obs date not null,
  heure_obs time not null,
  pluie_mm numeric(8,2) not null default 0,
  spores integer null,
  statut text not null check (statut in ('En cours','Validé','Pas de contamination')),
  comptage_termine boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.tavelure_parametres (
  id smallint primary key default 1 check (id = 1),
  suivi_termine boolean not null default false,
  date_fin date null,
  updated_at timestamptz not null default now()
);

insert into public.tavelure_parametres (id, suivi_termine, date_fin)
values (1, false, null)
on conflict (id) do nothing;

alter table public.tavelure_peritheces enable row level security;
alter table public.tavelure_comptages enable row level security;
alter table public.tavelure_parametres enable row level security;

-- Droits SQL de base.
grant select on public.tavelure_peritheces to anon, authenticated;
grant select on public.tavelure_comptages to anon, authenticated;
grant select on public.tavelure_parametres to anon, authenticated;

grant insert, update on public.tavelure_peritheces to authenticated;
grant insert, update, delete on public.tavelure_comptages to authenticated;
grant insert, update on public.tavelure_parametres to authenticated;
grant usage, select on sequence public.tavelure_comptages_id_seq to authenticated;

-- Lecture publique : aucun compte nécessaire.
drop policy if exists "Lecture publique périthèces" on public.tavelure_peritheces;
create policy "Lecture publique périthèces"
on public.tavelure_peritheces
for select
to anon, authenticated
using (true);

drop policy if exists "Lecture publique comptages" on public.tavelure_comptages;
create policy "Lecture publique comptages"
on public.tavelure_comptages
for select
to anon, authenticated
using (true);

drop policy if exists "Lecture publique paramètres" on public.tavelure_parametres;
create policy "Lecture publique paramètres"
on public.tavelure_parametres
for select
to anon, authenticated
using (true);

-- Écriture : uniquement un compte authentifié.
-- Aucun formulaire d'inscription n'existe dans SAM Tavelure.
-- Il faut aussi désactiver les inscriptions dans Supabase Auth pour que seuls
-- les comptes créés manuellement depuis Supabase puissent se connecter.
drop policy if exists "Écriture périthèces utilisateurs autorisés" on public.tavelure_peritheces;
create policy "Écriture périthèces utilisateurs autorisés"
on public.tavelure_peritheces
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Écriture comptages utilisateurs autorisés" on public.tavelure_comptages;
create policy "Écriture comptages utilisateurs autorisés"
on public.tavelure_comptages
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Écriture paramètres utilisateurs autorisés" on public.tavelure_parametres;
create policy "Écriture paramètres utilisateurs autorisés"
on public.tavelure_parametres
for all
to authenticated
using (true)
with check (true);
