create table if not exists public.tavelure_comptages (
  id bigint generated by default as identity primary key,
  episode text not null,
  date_obs date not null,
  heure_obs time not null,
  pluie_mm numeric(8,2) not null default 0,
  spores integer,
  statut text not null check (statut in ('En cours','Validé','Pas de contamination')),
  comptage_termine boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.tavelure_comptages enable row level security;

drop policy if exists "Lecture publique tavelure" on public.tavelure_comptages;
create policy "Lecture publique tavelure"
on public.tavelure_comptages
for select
to anon, authenticated
using (true);

drop policy if exists "Insertion admin tavelure" on public.tavelure_comptages;
create policy "Insertion admin tavelure"
on public.tavelure_comptages
for insert
to authenticated
with check (true);

drop policy if exists "Modification admin tavelure" on public.tavelure_comptages;
create policy "Modification admin tavelure"
on public.tavelure_comptages
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Suppression admin tavelure" on public.tavelure_comptages;
create policy "Suppression admin tavelure"
on public.tavelure_comptages
for delete
to authenticated
using (true);
